apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-traceability-irs

spec:
  roles:
    - name: team-admin
      description: All access to applications inside project-traceability-irs.
      jwtTokens:
        - exp: 1685985827
          iat: 1670433827
          id: ARGOCD_TOKEN_INT
      policies:
        - p, proj:project-traceability-irs:team-admin, applications, *, project-traceability-irs/*, allow
        - p, proj:project-traceability-irs:team-admin, exec, create, project-traceability-irs/*, allow
      groups:
        - catenax-ng:product-traceability-irs
    - name: read-only
      description: Read only access to the project
      policies:
        - p, proj:project-traceability-irs:read-only, applications, get, project-traceability-irs/*, allow
      groups:
        - catenax-ng:release-management
        - catenax-ng:test-management
